import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './layout/component/Header.jsx'
import Footer from './layout/component/Footer.jsx'
import { Toaster } from "react-hot-toast";

import { AuthProvider } from './context/Authcontext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* ✅ Wrap entire app with AuthProvider */}
        <AuthProvider>
          <Header />

          {/* Push content below sticky header */}
          <main className="pt-14 pb-16 md:pt-0 md:pb-0">
            <>
              <Toaster position="top-center" />
              {children}
            </>
          </main>

          <Footer />
        </AuthProvider>

      </body>
    </html>
  );
}
